name: Build ZMK Firmware

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        board: [seeeduino_xiao_ble]
        shield: [prospector_adapter]

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v3

      - name: Install prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build gperf ccache dfu-util device-tree-compiler wget \
              python3-pip python3-setuptools python3-wheel xz-utils file make gcc g++ git cmake
          pip3 install --upgrade pip
          pip3 install west

      - name: Initialize west workspace
        run: |
          west init -l config
          west update

      - name: Export Zephyr CMake package
        run: west zephyr-export

      - name: Build firmware
        run: |
          west build -s zmk/app -b ${{ matrix.board }} \
            -- -DSHIELD=${{ matrix.shield }} -DZMK_CONFIG=../../config
